### ISSUE TITLE
I need some help on the usage

### ISSUE THREAD

**Issue by EnanoFurtivo** [HoLLy-HaCKeR/osu-database-reader#11]
I managed to read a collection.db file this way :

using osu_database_reader.BinaryFiles;
CollectionDb cdb;
public Form1()
        {
            InitializeComponent();
            cdb = CollectionDb.Read(@"C:\Users\Larcho\Desktop\collection.db");
        }

wich gives me the list:
cdb.Collections[]

Now the thing is i dont know how to proceed to convert the Beatmap hashes into something usable.

**Comment by holly-hacker** [comment]
If you read osu.db too, you will get a list of beatmaps including path and beatmap hash. You can cross-reference them with the ones from the collection database.

**Comment by EnanoFurtivo** [comment]
**Thank you very muchhh!!** 

I only have one more question. Cross referencing two list would mean using a foreach statement to compare each item from one list to the other. Isn't there a more efficient way of doing this? Since most people playing osu have 20k+ maps, meaning that would take quite some time depending on the users collection.

**Comment by holly-hacker** [comment]
I guess you could sort the osu.db collection by MD5 and then use a binary search. That should bring the amount of array accesses down by a large amount. You could probably make it even faster by converting the MD5s to byte arrays or some kind of big integer, but I'm not sure if you really need that.

**Comment by EnanoFurtivo** [comment]
Is there any way you could add like a image property to the BeatmapEntry class, like the thumbnail path? or image name so i could do path + / + foldername + / + imagename. Im utilizing the thumbnails in my project and i have to do regex on the .osu file wich is very slow. With this library i reduced the loading times by more than half tho i still have to use regex on the beatmap file line by line to get that.
This is what i currently use:
Regular expresion parameter = @"([0,9]+\,[0,9]+)\,\""([^\""]+)\"".*"

**Comment by holly-hacker** [comment]
You can manually parse the file, which should be a lot faster than running a regex on every file. However, this issue isn't a support forum, you should probably look for help elsewhere. I'll be closing this issue now, create a new one if you have issues that are related to the library.
