### ISSUE TITLE
Impossible to find docs

### ISSUE THREAD

**Issue by AuracleTech** [HoLLy-HaCKeR/osu-database-reader#15]
There is no docs only code examples.

Can we have a small wiki https://github.com/HoLLy-HaCKeR/osu-database-reader/wiki

**Comment by holly-hacker** [comment]
You can look at the unit tests ([beatmaps](https://github.com/HoLLy-HaCKeR/osu-database-reader/blob/master/UnitTestProject/TestsText.cs), [.db files](https://github.com/HoLLy-HaCKeR/osu-database-reader/blob/master/UnitTestProject/TestsBinary.cs)) for an example on how to use the library. It's not very complex so most functionality can be found through intellisense too.
